### ISSUE TITLE
Overlapping items

### ISSUE THREAD

**Issue by braudy1100** [DevLight-Mobile-Agency/InfiniteCycleViewPager#11]
Is there any options to not make the items overlapping each other just like this one in your inspirations ..

![capture](https://cloud.githubusercontent.com/assets/13801097/18097323/01f08684-6f10-11e6-8abb-ac48b63f1bc5.PNG)

**Comment by GIGAMOLE** [comment]
Hello. Thanks for contact. You need cycle effect or slide?

**Comment by braudy1100** [comment]
@GIGAMOLE I need slide effect .. is it available?

**Comment by GIGAMOLE** [comment]
This library oriented to create cycle stack effect. If you need to create slide effect with neighbor visible items 
[here](http://stackoverflow.com/questions/10098040/android-viewpager-show-preview-of-page-on-left-and-right) or you can modify current page transformer with your own by using onInfiniteCyclePageTransformerListener.
