### ISSUE TITLE
How to increase the size of card in VerticalCycleViewPager?

### ISSUE THREAD

**Issue by Dule95D** [DevLight-Mobile-Agency/InfiniteCycleViewPager#13]
![14215367_1468399809840556_2037334976_o](https://cloud.githubusercontent.com/assets/13781045/18130909/2c797d62-6f91-11e6-9c1a-e43b9c0efe38.png)

Here is a code from main layout where is located vertical cycler view pager:

`<FrameLayout
        android:layout_above="@+id/bottom_menu_bar"
        android:id="@+id/frame_layout"
        android:layout_centerInParent="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.solaris.want2know.infinitecyclerviewpager.VerticalInfiniteCycleViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:icvp_interpolator="@android:anim/overshoot_interpolator"
            app:icvp_center_page_scale_offset="0dp"
            app:icvp_max_page_scale="0.9"
            app:icvp_medium_scaled="true"
            app:icvp_min_page_scale="0.7"
            app:icvp_min_page_scale_offset="-20dp"
            app:icvp_scroll_duration="500"/>

    </FrameLayout>`

And here is located item view for every card in vertical cycle view pager:

`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v7.widget.CardView
        android:layout_gravity="center"
        android:layout_width="match_parent"
        android:layout_height="300dp"
        app:cardUseCompatPadding="true"
        app:cardPreventCornerOverlap="false"
        app:cardCornerRadius="10dp"
        app:cardElevation="20dp">

        <ImageView
            android:id="@+id/image"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:layout_gravity="center"/>
    </android.support.v7.widget.CardView>

</FrameLayout>`

**Comment by GIGAMOLE** [comment]
Hello.
Thanks for contact.
So, what exactly do you need?

**Comment by GIGAMOLE** [comment]
As I see. There is no problem around.

**Comment by Dule95D** [comment]
I want to increase the size for this card a little bit more, but if i do that, white background of card i can see and my image i'm fetching from API is centered.

**Comment by GIGAMOLE** [comment]
You need to change height?

**Comment by GIGAMOLE** [comment]
You can set max scale to bigger value then 1.0F.

**Comment by GIGAMOLE** [comment]
Also you can try sample app and achieve similar effect with vertical ICVP where used correct bounds.

**Comment by Dule95D** [comment]
Thank you, i will try that.

**Comment by ghost** [comment]
Did you achieve to change card height? Im Having a similar issue where I want to keep scale width but a taller card...
