### ISSUE TITLE
Why to shield when the automatic change of the manual sliding events?

### ISSUE THREAD

**Issue by zengcanxiang** [DevLight-Mobile-Agency/InfiniteCycleViewPager#15]
Why to shield when the automatic change of the manual sliding events?

If you forget to click on it, I won't be able to switch to what I want, only waiting for the silly next chance next time. 

If the user hasn't finished it to the operation, the waiting time will be very long.....

```java 
public boolean onTouchEvent(final MotionEvent event) {
        if (mViewPageable.getAdapter() == null || mViewPageable.getAdapter().getCount() == 0)
            return false;
        if (mIsAutoScroll || mIsInitialItem || mViewPageable.isFakeDragging()) return false;
        if (event.getPointerCount() > MIN_POINTER_COUNT || !mViewPageable.hasWindowFocus())
            event.setAction(MotionEvent.ACTION_UP);
        checkHitRect(event);
        return true;
    }
```

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. Ok. Ill try to add delay feature later.

**Comment by zengcanxiang** [comment]
I think in the actual test case, if the user to touch the finger on the control, you can automatically pause the suspension is a very good experience. ^_^

**Comment by GIGAMOLE** [comment]
Ok. I will mind for better ux.
