### ISSUE TITLE
can i get like this view

### ISSUE THREAD

**Issue by nzala** [DevLight-Mobile-Agency/InfiniteCycleViewPager#17]
http://i.imgur.com/UsRIDlO.png

**Comment by GIGAMOLE** [comment]
Hi. This is my next library. Just wait. Thanks.

**Comment by nzala** [comment]
k
i wanted icarousel like view

**Comment by GIGAMOLE** [comment]
Yeah yeah. Like thia.

**Comment by nzala** [comment]
d u knw any segmented control in android like ios

**Comment by GIGAMOLE** [comment]
No. Currently nothing.

**Comment by nzala** [comment]
ok
