### ISSUE TITLE
Webview scroll issue

### ISSUE THREAD

**Issue by mehdok** [DevLight-Mobile-Agency/InfiniteCycleViewPager#18]
I have pages witch contain webview, the content of webviews are different in size. if the content does not fill the view everything is fine, with large content there is some glitch when scrolling. sometimes i scrolling down and suddenly webview scroll to its top. and every time i hold finger to select text the page getting scrolled as well.
any help or note would be appreciated.

note: i use `com.gigamole.infinitecycleviewpager.VerticalViewPager`

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
Its all about android. Can u provide any attachment.

**Comment by mehdok** [comment]
I record a video from the emulator, it's not too accurate beacuase of frame drop but you will get the idea of what is happening.
[Video](https://youtu.be/kCRcaXjk4NE)

**Comment by GIGAMOLE** [comment]
This example or your situation not response to ICVP. Its about WebView and it scroll.

**Comment by mehdok** [comment]
tnx for your answer,
but No, the `webview ` itself is OK, if i use same `webview `with normal `viewpager `everything is fine, scrolling and selecting have normal behavior. if i use `vertical viewpager` the problem shows up.  i tested with other vertical viewpager library and their situation is worse, the problem with this lib is more acceptable. If you need i can share any part of code with you, or i can send you APK, one with normal view pager and one with your library
