### ISSUE TITLE
Increase the card view layout_height

### ISSUE THREAD

**Issue by MrThiago** [DevLight-Mobile-Agency/InfiniteCycleViewPager#2]
Hello,

Is that possible to increase the height of the card view. instead of using icvp_max_page_scale.
then you could just apply a padding to left and right to be able to see the preview and next card ?
Because I am using this library for an table app only.
I have a lot white space on top and on bottom.

Thanks

I am using it Horizontal:

<com.gigamole.infinitecycleviewpager.HorizontalInfiniteCycleViewPager
            android:id="@+id/hicvp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/line_color"

            app:icvp_center_page_scale_offset="30dp"
            app:icvp_min_page_scale_offset="5dp"
            app:icvp_scroll_duration="1000"
            app:icvp_max_page_scale="0.9"
            app:icvp_min_page_scale="0.6"
            app:icvp_medium_scaled="false"/>

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question. Can you provide any screenshots, example?

**Comment by zhjian77** [comment]
app:icvp_center_page_scale_offset="30dp"
        app:icvp_min_page_scale_offset="5dp"
        app:icvp_scroll_duration="1000"
        app:icvp_max_page_scale="0.9"
        app:icvp_min_page_scale="0.6"
        app:icvp_medium_scaled="false"/>

**Comment by GIGAMOLE** [comment]
Its direct up to you. Layout width and height doesnt respond to icvp.
