### ISSUE TITLE
no interactive effect when i use infiniteCycleViewPager.notifyDataSetChanged()

### ISSUE THREAD

**Issue by KinaZhen** [DevLight-Mobile-Agency/InfiniteCycleViewPager#22]

**Comment by zjbpku** [comment]
the same issue even i override getItemPosition() and return POSITION_NONE, the content in infiniteCycleViewPager didn't update.

**Comment by zjbpku** [comment]
@KinaZhen  i solved the problem,  you can have a try. 
https://github.com/zjbpku/InfiniteCycleViewPager

**Comment by GIGAMOLE** [comment]
Later I will be check this up.
