### ISSUE TITLE
drop the bounceback effect

### ISSUE THREAD

**Issue by ZakTaccardi** [DevLight-Mobile-Agency/InfiniteCycleViewPager#4]
in a material world, we accelerate than decelerate. we don't run the stop sign, reverse, run it again by a lesser amount, then reverse into the correct position.

<3

**Comment by GIGAMOLE** [comment]
Hello. Thanks for a correct comment. ICVP based on inspired design which bring best of them. 
You can change interpolator to your own. Thanks.

**Comment by ZakTaccardi** [comment]
Awesome!
