### ISSUE TITLE
not smooth

### ISSUE THREAD

**Issue by xmuSistone** [DevLight-Mobile-Agency/InfiniteCycleViewPager#6]
Captured images looks wonderful, but when running on genuine android device, its fluency makes me sad. Your idea about displaying pages is creative, however, lacking of fluency is a fatal deficiency. Hope you can optimize it, and make it a great repository.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for this issue. Its all about android technics and methods. So I has one method bringToFront() and i'll do the best currently. Hope someone provide to me more improved ways to reach this effect on all devices.

**Comment by xmuSistone** [comment]
I mean fast switching pages is not consistent. BringtoFront should only affect the efficiency in the dragging part, not in the front-view-taking-over part. Later if i can help to improve this, i'll share the key point to u.

**Comment by GIGAMOLE** [comment]
Thanks.

**Comment by xmuSistone** [comment]
Hello, i forked this repository, and i have applied a new pull-request just now. I modified the touch event intercept principle by using a detector, this issue [Quick swipes easy open browser](https://github.com/DevLight-Mobile-Agency/InfiniteCycleViewPager/issues/5) is solved, and the front-view-switch section looks quite consistent and smooth. If there would help, u can merge the code.
